name: Sync VoucherVisionGO Client

on:
  push:
    branches:
      - main
    paths:
      - 'client.py'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VoucherVisionGO repository
        uses: actions/checkout@v3
        with:
          path: source-repo
          fetch-depth: 1

      - name: Checkout client-only repository
        uses: actions/checkout@v3
        with:
          repository: Gene-Weaver/VoucherVisionGO-client
          path: client-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Copy client.py and update README sync information
        run: |
          # Copy the client file
          cp source-repo/client.py client-repo/
          
          # Only update the sync timestamp in the README
          if [ -f client-repo/README.md ]; then
            # Use sed to replace or add the sync timestamp line
            grep -q "Last synchronized:" client-repo/README.md
            if [ $? -eq 0 ]; then
              # Replace existing timestamp line
              sed -i "s/Last synchronized:.*$/Last synchronized: $(date)/" client-repo/README.md
            else
              # Add timestamp after the "About" section
              sed -i "/## About/,/^$/s/^\(.*it is automatically synchronized.*\)$/\1\n\nLast synchronized: $(date)/" client-repo/README.md
            fi
          fi
          
          # Commit and push changes
          cd client-repo
          git config user.name "VoucherVision Bot"
          git config user.email "bot@github.com"
          git add client.py README.md
          git diff --staged --quiet || git commit -m "Sync client.py from VoucherVisionGO repository [$(date)]"
          git push